trigger:
  - main

pool:
  name: default

variables:
  pythonVersion: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'djangoapp'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'az_pipeline'
    appName: 'azure-pipeline'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
