trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
    python manage.py migrate --noinput
  displayName: 'Install dependencies and prepare app'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'djangoapp'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureDjangoDeploy'       # Name of service connection
    appName: 'mydjangoapp123'                    # Your App Service name
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
